version: '3'
services:
  db:
    image: mysql@sha256:68b207d01891915410db3b5bc1f69963e3dc8f23813fd01e61e6d7e7e3a46680
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: template
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: air -c .air.toml
    tty: true
    stdin_open: true
    ports:
      - '5001:5001'
    volumes:
      - ./app:/go/src/gin-jwt-template
      - pkg:/go/pkg
volumes:
  pkg:
    driver: local
